spring:
  application:
    name: backend
  datasource:
    url: jdbc:h2:mem:alten-db
  h2:
    console:
      enabled: true
server:
  port: 8080
jwt:
  secret: 9faa372517ac1d389758d3750fc07acf00f542277f26fec1ce4593e93f64e338
